name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "6a957714-92ff-45e0-848b-59cd16588a2f"

[version_metadata]
binding = "CF_VERSION_METADATA"

[observability.logs]
enabled = true
